services:
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"

  rustfs:
    image: rustfs/rustfs:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_ACCESS_KEY: admin
      RUSTFS_SECRET_KEY: admin123
    volumes:
      - rustfs_data:/data

  rustfs-bucket-init:
    image: minio/mc:latest
    depends_on:
      - rustfs
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      mc alias set rustfs http://rustfs:9000 admin admin123;
      mc mb --ignore-existing rustfs/uploads;
      mc anonymous set download rustfs/uploads;
      exit 0;
      "

volumes:
  rustfs_data:
